# Generated by Django 6.0.3 on 2026-03-12 18:33

import django.db.models.deletion
import django_advance_thumbnail.fields
import django_jsonform.models.fields
import garden.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Acknowledgements')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acknowledgements',
                'db_table': 'garden_config_acknowledgements',
            },
        ),
        migrations.CreateModel(
            name='ContextualEthicalFraming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Contextual and Ethical Framing')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contextual and Ethical Framing',
                'db_table': 'garden_config_contextual_ethical_framing',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='History of the SFU Indigenous Garden')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'History',
                'db_table': 'garden_config_history',
            },
        ),
        migrations.CreateModel(
            name='RelationalInterconnectedTeachings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Relational and Interconnected Teachings')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relational and Interconnected Teachings',
                'db_table': 'garden_config_relational_interconnected_teachings',
            },
        ),
        migrations.CreateModel(
            name='ResidentialSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Indian Residential Schools Map')),
                ('image', models.ImageField(blank=True, help_text='Please use <u><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types" target="_blank">standard web image types</a></u>. PNG, JPEG, and WebP are recommended.', null=True, upload_to='images/', verbose_name='Map Picture')),
                ('thumbnail', django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='thumbnails/')),
                ('image_caption', models.CharField(default='Residential Schools of Canada', verbose_name='Map Picture Caption')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indian Residential Schools Map',
                'db_table': 'garden_config_residential_schools',
            },
        ),
        migrations.CreateModel(
            name='WelcomePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Welcome to This Garden')),
                ('heading_halkomelem', models.CharField(blank=True, null=True)),
                ('heading_halkomelem_audio', garden.models.AsyncConstrainedFileField(blank=True, content_types=['application/octet-stream', 'audio/mpeg', 'audio/wav', 'audio/ogg'], help_text='Only MP3 (.mp3), WAV (.wav), or Ogg (.ogg) is allowed.', mime_lookup_length=4096, null=True, upload_to='audio/')),
                ('heading_squamish', models.CharField(blank=True, null=True)),
                ('heading_squamish_audio', garden.models.AsyncConstrainedFileField(blank=True, content_types=['application/octet-stream', 'audio/mpeg', 'audio/wav', 'audio/ogg'], help_text='Only MP3 (.mp3), WAV (.wav), or Ogg (.ogg) is allowed.', mime_lookup_length=4096, null=True, upload_to='audio/')),
                ('image', models.ImageField(blank=True, help_text='Please use <u><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types" target="_blank">standard web image types</a></u>. PNG, JPEG, and WebP are recommended.', null=True, upload_to='images/', verbose_name='Picture')),
                ('thumbnail', django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='thumbnails/')),
                ('image_caption', models.CharField(blank=True, null=True, verbose_name='Picture Caption')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welcome Popup',
                'db_table': 'garden_config_welcome_popup',
            },
        ),
        migrations.CreateModel(
            name='AcknowledgementsContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField()),
                ('list', django_jsonform.models.fields.ArrayField(base_field=models.CharField(), blank=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acknowledgements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='garden_config.acknowledgements')),
            ],
            options={
                'db_table': 'garden_config_acknowledgements_content_block',
                'ordering': ['order'],
            },
        ),
    ]
