# Generated by Django 6.0.3 on 2026-03-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='content',
        ),
        migrations.AddField(
            model_name='history',
            name='content_1',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction to History of the Garden Content'),
        ),
        migrations.AddField(
            model_name='history',
            name='content_2',
            field=models.TextField(blank=True, null=True, verbose_name='Design & Identifying the Plants Content'),
        ),
        migrations.AddField(
            model_name='history',
            name='content_3',
            field=models.TextField(blank=True, null=True, verbose_name='Usage of the Space Content'),
        ),
        migrations.AddField(
            model_name='history',
            name='content_4',
            field=models.TextField(blank=True, null=True, verbose_name='Ground Breaking Ceremony Content'),
        ),
        migrations.AddField(
            model_name='history',
            name='content_5',
            field=models.TextField(blank=True, null=True, verbose_name='Future Goals, Directions and Dreams Content'),
        ),
    ]
