# Generated by Django 6.0.3 on 2026-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_config', '0002_remove_history_content_history_content_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Overhead Map',
                'db_table': 'garden_config_overhead_map',
            },
        ),
    ]
