services:
  db:
    container_name: indigenous_garden_db
    image: postgres:17.4
    ports:
      - "15432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: indigenous_garden
      POSTGRES_USER: indigenous_garden
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U indigenous_garden -d indigenous_garden && psql -U indigenous_garden -d indigenous_garden -c 'SELECT 1;' || exit 1
      interval: 2s
      retries: 120

  redis:
    container_name: indigenous_garden_redis
    image: redis:7.4
    command: redis-server --appendonly yes
    volumes:
      - ./.data/redis:/data
    ports:
      - "16379:6379"
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 2s
      retries: 120

  nginx:
    container_name: indigenous_garden_nginx
    image: nginx:1.27
    volumes:
      # config
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      # mount app media and static content
      - .data/media:/media:ro
      # - .data/static:/static:ro # do not mount in development mode
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy

  vite:
    container_name: indigenous_garden_vite
    build:
      context: .
      target: indigenous-garden-vite
    command: yarn dev
    ports:
      - "5173:5173"
    volumes:
      # code for development
      - ./garden_vite:/app

      # use the container's node_modules folders (don't override with local dev)
      - /app/node_modules

  app: &app
    container_name: indigenous_garden_app
    # image: dhil/indigenous_garden
    build:
      context: .
      target: indigenous-garden
    volumes:
      # code for development
      - .:/app

      # files uploads
      - .data/media:/media
      # large static-assets
      - .data/static-assets:/static-assets

      # # persist static outside of container so it can be shared with nginx
      # - .data/static:/app/static # do not mount in development mode
    environment:
      DEBUG: True
      DB_HOST: db
      DB_NAME: indigenous_garden
      DB_USER: indigenous_garden
      DB_PASSWORD: password
      REDIS_HOST: redis
      EMAIL_HOST: mail
      EMAIL_HOST_USER: indigenous_garden
      EMAIL_HOST_PASSWORD: password
      MEDIA_FOLDER_UID: 101
      MEDIA_FOLDER_GID: 101
      GUNICORN_RELOAD: True
    healthcheck:
      test: curl --fail http://localhost/health_check/ || exit 1
      interval: 2s
      retries: 120
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    <<: *app
    container_name: indigenous_garden_worker
    command: ./manage.py rqworker default
    healthcheck:
      disable: true
    depends_on:
      app:
        condition: service_healthy

  mail:
    container_name: indigenous_garden_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"