# Generated by Django 4.2.7 on 2023-11-24 20:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import safe_filefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image or provide an image url. If both are present, only the image upload will be used', null=True, upload_to='images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_license', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'garden_image',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('english_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('english_names_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='English audio')),
                ('english_content', models.TextField()),
                ('english_content_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='English audio')),
                ('western_scientific_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('western_scientific_names_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='Western scientific audio')),
                ('halkomelem_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None, verbose_name='hən̓q̓əmin̓əm̓ names')),
                ('halkomelem_names_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='hən̓q̓əmin̓əm̓ audio')),
                ('halkomelem_content', models.TextField(blank=True, verbose_name='hən̓q̓əmin̓əm̓ content')),
                ('halkomelem_content_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='hən̓q̓əmin̓əm̓ audio')),
                ('squamish_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None, verbose_name='Sḵwx̱wú7mesh Sníchim label')),
                ('squamish_names_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='Sḵwx̱wú7mesh Sníchim audio')),
                ('squamish_content', models.TextField(blank=True, verbose_name='Sḵwx̱wú7mesh Sníchim content')),
                ('squamish_content_audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/', verbose_name='Sḵwx̱wú7mesh Sníchim audio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'garden_plant',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='garden.plant')),
            ],
            options={
                'db_table': 'garden_point',
            },
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['number'], name='garden_plan_number_684713_idx'),
        ),
        migrations.AddField(
            model_name='image',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.plant'),
        ),
    ]
