# Generated by Django 4.2.7 on 2024-01-23 23:28

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import safe_filefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('color', colorfield.fields.ColorField(default='#7cb341', image_field=None, max_length=25, samples=None)),
                ('feature_type', models.CharField(choices=[('PLANT', 'Plant'), ('GARDEN_FEATURE', 'Garden Feature')], default='PLANT', max_length=255)),
                ('audio', safe_filefield.models.SafeFileField(blank=True, null=True, upload_to='audio/')),
                ('english_names', django_jsonform.models.fields.JSONField()),
                ('western_scientific_names', django_jsonform.models.fields.JSONField(blank=True)),
                ('halkomelem_names', django_jsonform.models.fields.JSONField(blank=True, verbose_name='hən̓q̓əmin̓əm̓ names')),
                ('squamish_names', django_jsonform.models.fields.JSONField(blank=True, verbose_name='Sḵwx̱wú7mesh Sníchim names')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'garden_feature',
            },
        ),
        migrations.CreateModel(
            name='PanoramaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_points', to='garden.feature')),
            ],
            options={
                'db_table': 'garden_panorama_point',
            },
        ),
        migrations.CreateModel(
            name='OverheadPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_points', to='garden.feature')),
            ],
            options={
                'db_table': 'garden_overhead_point',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image or provide an image url. If both are present, only the uploaded image will be used', null=True, upload_to='images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_license', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.feature')),
            ],
            options={
                'db_table': 'garden_feature_image',
            },
        ),
    ]
