# Generated by Django 5.0.8 on 2024-09-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_alter_point_feature_alter_point_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
