# Generated by Django 5.1.6 on 2025-03-13 05:00

import admin_async_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_feature_references_alter_feature_captions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='video_original',
            field=admin_async_upload.models.AsyncFileField(blank=True, null=True, upload_to='videos/', verbose_name='video'),
        ),
        migrations.AddField(
            model_name='feature',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='video_thumbnails_vtt',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
