# Generated by Django 5.1.7 on 2025-03-28 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_remove_feature_captions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-y', 'x'], 'verbose_name': 'Overhead Point'},
        ),
        migrations.CreateModel(
            name='Location1PanoramaPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_1_panorama_points', to='garden.feature')),
            ],
            options={
                'verbose_name': 'Fire Pit Panorama Point',
                'db_table': 'garden_feature_location_1_panorama_point',
            },
        ),
        migrations.CreateModel(
            name='Location2PanoramaPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_2_panorama_points', to='garden.feature')),
            ],
            options={
                'verbose_name': 'Location 2 Panorama Point',
                'db_table': 'garden_feature_location_2_panorama_point',
            },
        ),
        migrations.CreateModel(
            name='Location3PanoramaPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_3_panorama_points', to='garden.feature')),
            ],
            options={
                'verbose_name': 'Location 3 Panorama Point',
                'db_table': 'garden_feature_location_3_panorama_point',
            },
        ),
    ]
