# Generated by Django 6.0.8 on 2026-09-01 18:43

import django.db.models.deletion
import django_dh_map.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_dh_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockMultilingualLabels',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
            ],
            options={
                'verbose_name': 'Multilingual Labels',
                'db_table': 'indigenous_garden_app_cb_multilingual_labels',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='WelcomeModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome')),
                ('display', models.BooleanField(db_index=True, default=False, verbose_name='Display?')),
                ('close_button_label', models.CharField(default='Close')),
            ],
            options={
                'verbose_name': 'Welcome Modal',
                'db_table': 'indigenous_garden_app_welcome_modal',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockMultilingualLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('language', models.CharField(choices=[('english', 'English'), ('western_scientific', 'Western Scientific'), ('halkomelem', 'hən̓q̓əmin̓əm̓'), ('squamish', 'Sḵwx̱wú7mesh Sníchim')])),
                ('label', models.CharField(max_length=255)),
                ('descriptor', models.CharField(blank=True, max_length=255, null=True)),
                ('original', django_dh_map.fields.AsyncFFileField(blank=True, help_text='Please use a high quality audio.', max_length=255, null=True, upload_to='audio/', verbose_name='High Quality Audio')),
                ('audio_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='label_audio_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/audio'))),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('multilingual_labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='indigenous_garden_app.contentblockmultilinguallabels')),
            ],
            options={
                'verbose_name': 'Label',
                'db_table': 'indigenous_garden_app_cb_multilingual_label',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeModalContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('welcome_modal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_item', to='indigenous_garden_app.welcomemodal')),
            ],
            options={
                'verbose_name': 'Welcome Modal Content',
                'db_table': 'indigenous_garden_app_ci_welcome_modal',
            },
            bases=('django_dh_map.contentitem',),
        ),
    ]
